service: tsu

provider:
  name: aws
  runtime: python3.6
  iamRoleStatements:
      - Effect: Allow
        Action:
          - lambda:InvokeFunction
        Resource: "*"

package:
  individually: true
  exclude:
    - ".*/**"

functions:
  core_posts_listing:
    handler: src/core/posts/listing.handler
    name: tsu-core-posts-listing
    package:
      include:
        - src/core/posts/**

  api_posts:
    handler: src/api/posts.handler
    name: tsu-api-posts
    events:
      - http: GET /api/posts
    package:
      include:
        - src/api/**
        - src/util/**

  api_get_env_var:
    handler: src/api/env_var.handler
    name: tsu-env-var
    events:
      - http: GET /api/env_var
    package:
      include:
        - src/api/**
